version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile_backend
    ports:
      - "5000:5000"
    container_name: music_backend
    environment:
      - FLASK_ENV=development

  frontend:
    build:
      context: .
      dockerfile: Dockerfile_frontend
    ports:
      - "8501:8501"
    container_name: music_frontend
    depends_on:
      - backend
    environment:
      - STREAMLIT_SERVER_PORT=8501
