# Use a Python base image
FROM python:3.9-slim

# Set the working directory
WORKDIR /app

# Copy the frontend requirements and install them
COPY requirements_frontend.txt .
RUN pip install -r requirements_frontend.txt

# Copy the Streamlit code
COPY streamlit_app.py .

# Expose the Streamlit port
EXPOSE 8501

# Run the Streamlit app
CMD ["streamlit", "run", "streamlit_app.py"]
