version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile_backend
    container_name: emotion_music_backend
    ports:
      - "5000:5000"
    env_file:
      - .env
    networks:
      - app-network

  frontend:
    build:
      context: .
      dockerfile: Dockerfile_frontend
    container_name: emotion_music_frontend
    ports:
      - "8501:8501"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

