# Use a Python base image
FROM python:3.9-slim

# Set the working directory
WORKDIR /app

# Copy the backend requirements and install them
COPY requirements_backend.txt .
RUN pip install -r requirements_backend.txt

# Copy the backend code
COPY app.py .

# Expose the Flask port
EXPOSE 5000

# Run the Flask app
CMD ["gunicorn", "--bind", "0.0.0.0:5000", "app:app"]
